export const CUBE_CARDS: string[] = [
  "Giver of Runes","March of Otherworldly Light","Kytheon, Hero of Akros","Kinscaer Sentry","Mother of Runes",
  "Touch the Spirit Realm","Ocelot Pride","Cathar Commando","Intrepid Adversary","Witch Enchanter",
  "Glimmer Lens","Phelia, Exuberant Shepherd","Earth Kingdom Jailer","Splitskin Doll","Sanguine Evangelist",
  "Stoneforge Mystic","Thalia, Guardian of Thraben","Voice of Victory","Adeline, Resplendent Cathar","Static Prison",
  "Staff of the Storyteller","Flickerwisp","Loran of the Third Path","Monastery Mentor","Containment Priest",
  "Skyclave Apparition","Lion Sash","Enduring Innocence","Palace Jailer","Elite Spellbinder",
  "Overlord of the Mistmoors","Serra Paragon","The Wandering Emperor","Sheltered by Ghosts","Sage of the Skies",
  "Solitude","Enlightened Tutor","Mana Tithe","Path to Exile","Swords to Plowshares",
  "Get Lost","Ephemerate","Prismatic Ending","Balance","Council's Judgment",
  "Beza, the Bounding Spring","Reprieve","Day of Judgment","Winds of Abandon","Wrath of God",
  "Mox Pearl","Portable Hole","Erode","Swift Reconfiguration","Parallax Wave",
  "Elspeth, Storm Slayer","Karakas","Jace, Vryn's Prodigy","Duelist of the Mind","Tishana's Tidebinder",
  "Snapcaster Mage","Thundertrap Trainer","Thieving Skydiver","Malcolm, Alluring Scoundrel","Quantum Riddler",
  "Hullbreacher","Faerie Mastermind","Subtlety","Vendilion Clique","Kappa Cannoneer",
  "Tamiyo, Inquisitive Student","Urza, Lord High Artificer","Condescend","Wan Shi Tong, Librarian","Narset, Parter of Veils",
  "Jace, the Mind Sculptor","Time Warp","Daze","Force of Negation","Force of Will",
  "Ancestral Recall","Brainstorm","Consider","Spell Pierce","Mystical Tutor",
  "Three Steps Ahead","Arcane Denial","Brazen Borrower","Counterspell","Glen Elendra Guardian",
  "Lose Focus","Mana Drain","Mana Leak","Memory Lapse","Miscalculation",
  "Remand","Flash","Mystic Confluence","Consult the Star Charts","Lórien Revealed",
  "Enduring Curiosity","Ponder","Preordain","Sleight of Hand","Thirst for Discovery",
  "Time Walk","Show and Tell","Timetwister","Tinker","Bribery",
  "Time Spiral","Stock Up","Mox Sapphire","Trinket Mage","Echo of Eons",
  "Opposition","Flow State","Chrome Host Seedshark","Otawara, Soaring City","Tolarian Academy",
  "Elegy Acolyte","Caustic Bronco","Collective Brutality","Deep-Cavern Bat","Kitesail Freebooter",
  "Concealing Curtains","Shallow Grave","Emperor of Bones","Barrowgoyf","Dark Confidant",
  "Dauthi Voidwalker","Harvester of Misery","Corpse Dance","Pack Rat","Valki, God of Lies",
  "Jadar, Ghoulcaller of Nephalia","Lord Skitter, Sewer King","Woe Strider","Preacher of the Schism","Murderous Cut",
  "Orcish Bowmasters","Unearth","Sheoldred, the Apocalypse","Custodi Lich","Necron Deathmark",
  "Crabomination","Archon of Cruelty","Griselbrand","Liliana of the Veil","Bone Shards",
  "Cut Down","Dismember","Entomb","Fatal Push","Vampiric Tutor",
  "Bitter Triumph","Night's Whisper","Infernal Grasp","Grief","Bloodchief's Thirst",
  "Imperial Seal","Inquisition of Kozilek","Reanimate","Thoughtseize","Virtue of Persistence",
  "Demonic Tutor","Exhume","Duress","Toxic Deluge","Damnation",
  "Persist","Life // Death","Mind Twist","Mox Jet","Animate Dead",
  "Bitterblossom","Dance of the Dead","Necromancy","Recurring Nightmare","Snuff Out",
  "Legion Extruder","Dragon's Rage Channeler","Trumpeting Carnosaur","Chainsaw","Goblin Welder",
  "Glorybringer","Improvisation Capstone","Kellan, Planar Trailblazer","Ragavan, Nimble Pilferer","Hired Claw",
  "Searslicer Goblin","Generous Plunderer","Mine Collapse","Flametongue Yearling","Magda, Brazen Outlaw",
  "Draconautics Engineer","Kari Zev, Skyship Raider","Ivora, Insatiable Heir","Fable of the Mirror-Breaker","Goblin Rabblemaster",
  "Legion Warboss","Flame Slash","Fear of Missing Out","Laelia, the Blade Reforged","Death-Greeter's Champion",
  "Screaming Nemesis","Unholy Heat","Hexing Squelcher","Flametongue Kavu","Hellrider",
  "Headliner Scarlett","Broadside Bombardiers","Siege-Gang Commander","Pyrogoyf","Goldspan Dragon",
  "Chandra, Torch of Defiance","Ghostfire Slice","Gut, True Soul Zealot","Burst Lightning","Lightning Bolt",
  "Abrade","Bonecrusher Giant","Sear","Galvanic Blast","Spinerock Tyrant",
  "Redirect Lightning","Fury","Chain Lightning","Bomat Courier","Faithless Looting",
  "Cinder Strike","Cori-Steel Cutter","Wheel of Fortune","Fiery Confluence","Thunder Magic",
  "Mox Ruby","Voldaren Epicure","Purphoros, God of the Forge","Sneak Attack","Arena of Glory",
  "Galvanic Discharge","Six","Elvish Reclaimer","Birds of Paradise","Elvish Mystic",
  "Bristly Bill, Spine Sower","Fyndhorn Elves","Noble Hierarch","Hexdrinker","Vaultborn Tyrant",
  "Ignoble Hierarch","Llanowar Elves","Great Divide Guide","Fauna Shaman","Lotus Cobra",
  "Rofellos, Llanowar Emissary","Sakura-Tribe Elder","Badgermole Cub","Delighted Halfling","Keen-Eyed Curator",
  "Scythecat Cub","Sylvan Safekeeper","Eternal Witness","Ramunap Excavator","Ursine Monstrosity",
  "Formidable Speaker","Esika's Chariot","Haywire Mite","Questing Beast","Toski, Bearer of Secrets",
  "Deep Forest Hermit","Deranged Hermit","Titania, Protector of Argoth","Old One Eye","Overlord of the Hauntwoods",
  "Worldspine Wurm","Titan of Industry","Craterhoof Behemoth","Woodfall Primus","Garruk Wildspeaker",
  "Nissa, Who Shakes the World","Worldly Tutor","Pest Infestation","Channel","Oath of Druids",
  "Regrowth","Natural Order","Green Sun's Zenith","Mox Emerald","Rancor",
  "Sentinel of the Nameless City","Malevolent Rumble","Survival of the Fittest","Sylvan Library","Boseiju, Who Endures",
  "Gaea's Cradle","Ouroboroid","Floodfarm Verge","Celestial Colonnade","Flooded Strand",
  "Hallowed Fountain","Meticulous Archive","Seachrome Coast","Tundra","Aang, Swift Savior",
  "Talisman of Progress","Teferi, Time Raveler","Fractured Identity","Undercity Sewers","Creeping Tar Pit",
  "Gloomlake Verge","Polluted Delta","Darkslick Shores","Underground Sea","Watery Grave",
  "Baleful Strix","Ertai Resurrected","Talisman of Dominance","Fallen Shinobi","Badlands",
  "Blackcleave Cliffs","Raucous Theater","Blood Crypt","Bloodstained Mire","Blazemire Verge",
  "Restless Vents","Fire Covenant","Talisman of Indulgence","Daretti, Ingenious Iconoclast","Kolaghan's Command",
  "Chaos Defiler","Thornspire Verge","Commercial District","Copperline Gorge","Restless Ridgeline",
  "Stomping Ground","Taiga","Wooded Foothills","Manamorphose","Mawloc",
  "Talisman of Impulse","Vibrance","Minsc & Boo, Timeless Heroes","Lush Portico","Hushwood Verge",
  "Savannah","Restless Prairie","Temple Garden","Windswept Heath","Mirari's Wake",
  "Figure of Fable","Talisman of Unity","Knight of Autumn","Shadowy Backstreet","Restless Fortress",
  "Godless Shrine","Marsh Flats","Scrubland","Bleachbone Verge","Concealed Courtyard",
  "Abigale, Eloquent First-Year","Lurrus of the Dream-Den","Talisman of Hierarchy","Tidehollow Sculler","Vindicate",
  "Fiery Islet","Thundering Falls","Scalding Tarn","Spirebluff Canal","Steam Vents",
  "Volcanic Island","Riverpyre Verge","Saheeli, Sublime Artificer","Expressive Iteration","Talisman of Creativity",
  "Lutri, the Spellchaser","Dack Fayden","Bayou","Underground Mortuary","Wastewood Verge",
  "Blooming Marsh","Restless Cottage","Overgrown Tomb","Verdant Catacombs","Abrupt Decay",
  "Assassin's Trophy","Mosswood Dreadknight","Talisman of Resilience","Grist, the Hunger Tide","Arid Mesa",
  "Inspiring Vantage","Forth Eorlingas!","Elegant Parlor","Plateau","Sacred Foundry",
  "Sunbaked Canyon","Phlage, Titan of Fire's Fury","Comet, Stellar Pup","Rip Apart","Talisman of Conviction",
  "Hedge Maze","Breeding Pool","Restless Vinestalk","Misty Rainforest","Tropical Island",
  "Willowrush Verge","Botanical Sanctum","Wistfulness","Talisman of Curiosity","Oko, Thief of Crowns",
  "Nadu, Winged Wisdom","Auroral Procession","Spara's Headquarters","Raffine's Tower","Sphinx of the Steel Wind",
  "Xander's Lounge","Nicol Bolas, the Ravager","Ziatora's Proving Ground","Jetmir's Garden","Sin, Spira's Punishment",
  "Savai Triome","Ketria Triome","Loot, the Pathfinder","Indatha Triome","Inkwell Leviathan",
  "Raugrin Triome","Shorikai, Genesis Engine","Zagoth Triome","Leovold, Emissary of Trest","Etali, Primal Conqueror",
  "Unlicensed Hearse","Jeskai Revelation","Ugin, Eye of the Storms","Phyrexian Revoker","Reckoner Bankbuster",
  "Urza's Bauble","Triplicate Titan","Wurmcoil Engine","Myr Battlesphere","Blightsteel Colossus",
  "Emrakul, the Aeons Torn","Sundering Titan","Ulamog, the Ceaseless Hunger","Ulamog, the Infinite Gyre","Karn, Scion of Urza",
  "Tezzeret, Cruel Captain","Black Lotus","Chrome Mox","Mana Crypt","Mishra's Bauble",
  "Mox Diamond","Zuran Orb","Lightning Greaves","Currency Converter","Coveted Jewel",
  "Mana Vault","Nexus of Becoming","Retrofitter Foundry","Sensei's Divining Top","Skullclamp",
  "Sol Ring","Pentad Prism","Grim Monolith","Smuggler's Copter","Umezawa's Jitte",
  "Winter Orb","Mox Opal","Coalition Relic","Crucible of Worlds","City of Traitors",
  "Relic of Sauron","Sword of Fire and Ice","Buster Sword","The Mightstone and Weakstone","Candelabra of Tawnos",
  "The Endstone","Kaldra Compleat","Nettlecyst","Memory Jar","Chromatic Star",
  "Ancient Tomb","Ash Barrens","City of Brass","Fabled Passage","Starting Town",
  "Library of Alexandria","Mana Confluence","Maze of Ith","Multiversal Passage","Mishra's Workshop",
  "Prismatic Vista","Rishadan Port","Strip Mine","Urza's Saga","Wasteland",
  "Showdown of the Skalds","Karn Liberated","Booster Tutor","Shadowspear","Lotus Petal",
  "Portal to Phyrexia","Ajani, Nacatl Pariah","Teferi, Hero of Dominaria","Consecrated Sphinx","Pyrokinesis",
  "Isochron Scepter","Inti, Seneschal of the Sun","Torsten, Founder of Benalia","Sandstorm Salvager","Elder Gargaroth",
  "Sowing Mycospawn","Esper Origins","Fastbond","Thraben Inspector","Mirror Entity",
  "Yawgmoth, Thran Physician","Phyrexian Metamorph","Scuzzback Scrounger","Tersa Lightshatter","Sheoldred's Edict",
  "Razorverge Thicket","Springheart Nantuko","Cosmogrand Zenith","Virtue of Loyalty","Sunfall",
  "Planar Disruption","Guide of Souls","Cankerbloom","Atraxa, Grand Unifier","Dark Ritual",
  "Psychic Frog","Icetill Explorer","The One Ring","Sire of Seven Deaths","Crop Rotation",
  "The Rise of Sozin","Troll of Khazad-dûm","Esper Sentinel","Oliphaunt","Generous Ent",
];
