export interface WeekInfo {
  week: number;
  sizeComparison: string;
  sizeEmoji: string;
  babyDevelopment: string;
  momChanges: string;
  funFact: string;
}

export const pregnancyWeeks: WeekInfo[] = [
  { week: 4, sizeComparison: 'poppy seed', sizeEmoji: '🌱', babyDevelopment: 'The embryo has just implanted. The neural tube, which becomes the brain and spinal cord, is beginning to form.', momChanges: 'You may not feel much yet, but your body is working hard! Fatigue and tender breasts might start.', funFact: 'Your baby is about 1mm long — smaller than a grain of rice!' },
  { week: 5, sizeComparison: 'apple seed', sizeEmoji: '🌿', babyDevelopment: 'The heart has begun beating! The tiny heart is pumping blood for the very first time. Brain, spinal cord, and other organs are starting to form.', momChanges: 'Morning sickness may begin. Your sense of smell might become heightened. Rest as much as you can.', funFact: 'The heart starts beating around day 22 — even before you\'ve missed your period!' },
  { week: 6, sizeComparison: 'pea', sizeEmoji: '🫛', babyDevelopment: 'Facial features are forming — dark spots where eyes will be, small pits for the ears. Arm and leg buds are appearing. The heart now has four chambers!', momChanges: 'Nausea may be in full swing. Food aversions and cravings can begin. The uterus is about the size of a plum.', funFact: 'Baby\'s heart is beating about 110 times per minute — nearly twice as fast as yours!' },
  { week: 7, sizeComparison: 'blueberry', sizeEmoji: '🫐', babyDevelopment: 'The brain is growing rapidly — generating about 100 new brain cells every minute! Hands and feet are starting to form, with tiny ridges that will become fingers.', momChanges: 'Fatigue is common as your body works overtime. The uterus has doubled in size since conception.', funFact: 'Baby\'s brain is growing so fast it temporarily makes the head larger than the rest of the body!' },
  { week: 8, sizeComparison: 'raspberry', sizeEmoji: '🍓', babyDevelopment: 'Fingers and toes are forming! All major organs are present, though still developing. The embryo can now make small, spontaneous movements.', momChanges: 'Your uterus is now the size of a large orange. You might notice your waistbands getting tighter.', funFact: 'At 8 weeks, baby has taste buds! They can already sense the flavors in the amniotic fluid.' },
  { week: 9, sizeComparison: 'grape', sizeEmoji: '🍇', babyDevelopment: 'Bones are beginning to form, replacing the cartilage. Baby\'s head is more upright now. Tiny earlobes are visible.', momChanges: 'You may notice your bra size increasing. Mood swings are normal as hormones fluctuate.', funFact: 'From now on, baby is officially called a "fetus" instead of an embryo!' },
  { week: 10, sizeComparison: 'kumquat', sizeEmoji: '🍊', babyDevelopment: 'All organs, limbs, muscles, and bones are in place. Baby can now swallow and kick! The critical development period is almost over.', momChanges: 'The first trimester is almost done! Your blood volume is increasing significantly.', funFact: 'Baby\'s fingerprints are already forming — completely unique, just like they\'ll be for life!' },
  { week: 11, sizeComparison: 'fig', sizeEmoji: '🌰', babyDevelopment: 'Baby can open and close their fists. Tooth buds are forming. The diaphragm is developing, which means hiccups could start!', momChanges: 'Nausea may start to ease for many moms. Energy levels often improve in the coming weeks.', funFact: 'Baby hiccups can start now — you might feel them as little rhythmic flutters later!' },
  { week: 12, sizeComparison: 'lime', sizeEmoji: '🍋', babyDevelopment: 'The digestive system is starting to practice. Reflexes are developing. Baby\'s kidneys are producing urine.', momChanges: 'Most miscarriage risk has passed. You might start showing soon! The pregnancy glow often begins.', funFact: 'This week marks the end of the most critical development period — the biggest risk is now behind you!' },
  { week: 13, sizeComparison: 'lemon', sizeEmoji: '🍋', babyDevelopment: 'The vocal cords are forming. Facial muscles are developing. Baby can make facial expressions!', momChanges: 'Welcome to the second trimester! Energy often returns. Time to start thinking about maternity clothes.', funFact: 'The second trimester is often called the "honeymoon phase" — nausea fades and energy returns!' },
  { week: 14, sizeComparison: 'peach', sizeEmoji: '🍑', babyDevelopment: 'Baby is making facial expressions. The sex may be visible on ultrasound. Baby can squint, frown, and grimace.', momChanges: 'Your belly is growing! Some moms feel the baby move as light flutters.', funFact: 'Baby can suck their thumb! Ultrasounds often catch babies in this adorable pose.' },
  { week: 15, sizeComparison: 'apple', sizeEmoji: '🍎', babyDevelopment: 'Baby can sense light even though the eyes are still fused shut. Bones are getting harder. The legs are now longer than the arms.', momChanges: 'You might experience round ligament pain as your uterus grows. This is normal!', funFact: 'Baby can detect bright light outside the womb — shine a flashlight on your belly and they might react!' },
  { week: 16, sizeComparison: 'avocado', sizeEmoji: '🥑', babyDevelopment: 'Baby can hear! They can hear your heartbeat, your voice, and external sounds. Strong kicks may begin.', momChanges: 'This is often when the anatomy ultrasound happens. Many parents find out the sex around now!', funFact: 'Singing or reading to your baby now has real benefits — they\'ll recognize your voice at birth!' },
  { week: 17, sizeComparison: 'pear', sizeEmoji: '🍐', babyDevelopment: 'Brown fat is accumulating to keep baby warm. Fingerprints are now complete. The umbilical cord is getting stronger.', momChanges: 'Your center of gravity is shifting. Heartburn might begin as the uterus presses up.', funFact: 'Baby\'s fingerprints are fully formed and are completely unique — even identical twins have different fingerprints!' },
  { week: 18, sizeComparison: 'bell pepper', sizeEmoji: '🫑', babyDevelopment: 'Baby is yawning and hiccupping regularly. The ears are now in their final position. Myelin is beginning to form on nerves.', momChanges: 'You might feel stronger kicks and movements. Sleep on your side to improve blood flow.', funFact: 'Baby can hear music now! Studies show newborns recognize songs they heard in the womb.' },
  { week: 19, sizeComparison: 'mango', sizeEmoji: '🥭', babyDevelopment: 'A protective coating called vernix caseosa is forming. All five senses are developing rapidly.', momChanges: 'Halfway there next week! You should be feeling regular movements by now.', funFact: 'The vernix coating protects baby\'s delicate skin from the amniotic fluid and helps with delivery!' },
  { week: 20, sizeComparison: 'banana', sizeEmoji: '🍌', babyDevelopment: 'Halfway there! Baby is swallowing amniotic fluid and their digestive system is practicing. They can hear your voice clearly now.', momChanges: 'Your uterus is now at your belly button. The anatomy scan usually happens around this week.', funFact: 'Halfway milestone! Baby has been growing for 20 weeks and has about 20 more weeks to go before meeting you!' },
  { week: 21, sizeComparison: 'carrot', sizeEmoji: '🥕', babyDevelopment: 'Baby\'s eyebrows and eyelids are fully formed. The digestive system is developing, preparing for life outside.', momChanges: 'Your belly button may start to pop out. Leg cramps at night are common.', funFact: 'Baby can now taste what you eat through the amniotic fluid! Spicy or sweet flavors pass right through.' },
  { week: 22, sizeComparison: 'papaya', sizeEmoji: '🍈', babyDevelopment: 'Baby\'s sense of touch is developing rapidly. The brain is developing very quickly. Lanugo (fine downy hair) covers the body.', momChanges: 'Swelling in feet and ankles is normal. Stay hydrated and put your feet up!', funFact: 'Baby\'s grip is now strong enough to grab their umbilical cord — they often do this in ultrasound images!' },
  { week: 23, sizeComparison: 'grapefruit', sizeEmoji: '🍊', babyDevelopment: 'Baby\'s hearing is fully developed — they can respond to your voice and loud noises. They may move in response to music.', momChanges: 'Braxton Hicks contractions (practice contractions) may begin. They should be painless and irregular.', funFact: 'If your partner puts their ear to your belly, they might actually hear baby\'s heartbeat!' },
  { week: 24, sizeComparison: 'ear of corn', sizeEmoji: '🌽', babyDevelopment: 'VIABILITY MILESTONE! Lungs are developing the surfactant needed to breathe air. Brain is developing rapidly. Taste buds are fully formed.', momChanges: 'You should be feeling kicks regularly. Count them — at least 10 movements within 2 hours is ideal.', funFact: 'Week 24 is a major milestone — babies born this week have a chance of survival with medical help!' },
  { week: 25, sizeComparison: 'acorn squash', sizeEmoji: '🎃', babyDevelopment: 'Baby is getting less wrinkly as fat accumulates. They have a regular sleep-wake cycle. Nostrils are opening.', momChanges: 'Glucose tolerance test is usually done around now. Backaches may increase.', funFact: 'Baby now has a sleep schedule — you might notice patterns of when they\'re most active!' },
  { week: 26, sizeComparison: 'lettuce', sizeEmoji: '🥬', babyDevelopment: 'Eyes are opening and baby can blink! They can see light and dark through your belly. Brain activity is increasing significantly.', momChanges: 'Third trimester is approaching! You might feel short of breath as the uterus presses up against your lungs.', funFact: 'Baby\'s eyes are opening for the first time — they\'re starting to see light and shadow!' },
  { week: 27, sizeComparison: 'cauliflower', sizeEmoji: '🥦', babyDevelopment: 'Brain tissue is developing rapidly. Baby can recognize your voice. They are practicing breathing motions.', momChanges: 'Sleep can be challenging — try a pregnancy pillow for support. Rest when you can!', funFact: 'Your baby can now recognize the difference between your voice and others\' — you\'re already their favorite!' },
  { week: 28, sizeComparison: 'eggplant', sizeEmoji: '🍆', babyDevelopment: 'Baby can dream! REM sleep is present. Eyelashes and eyebrows are visible. The brain is developing rapidly.', momChanges: 'Welcome to the third trimester! Doctor visits will become more frequent now.', funFact: 'At 28 weeks, babies born early have an 80%+ survival rate — your little one is really gaining strength!' },
  { week: 29, sizeComparison: 'butternut squash', sizeEmoji: '🎃', babyDevelopment: 'Baby is developing a regular kicking schedule. Muscles and lungs are maturing. Baby can grip strongly.', momChanges: 'Frequent urination returns as the baby grows and presses on your bladder.', funFact: 'Count your baby\'s kicks! Aim to feel at least 10 movements within 2 hours.' },
  { week: 30, sizeComparison: 'cabbage', sizeEmoji: '🥬', babyDevelopment: 'The brain is growing faster than ever. Baby is storing iron, calcium, and phosphorus. Lanugo is starting to disappear.', momChanges: 'Colostrum (pre-milk) may start leaking from your breasts. Your body is preparing!', funFact: 'Baby\'s brain is growing so fast right now, developing all the folds and wrinkles of a mature brain!' },
  { week: 31, sizeComparison: 'coconut', sizeEmoji: '🥥', babyDevelopment: 'All five senses are working now. Baby can process information from the environment. The immune system is developing.', momChanges: 'You may feel more pelvic pressure. A slight increase in discharge is normal.', funFact: 'Baby has a complete set of senses now — touch, taste, smell, hearing, and even limited vision!' },
  { week: 32, sizeComparison: 'squash', sizeEmoji: '🫑', babyDevelopment: 'Baby is practicing breathing movements regularly. Fingernails have reached the fingertips. Gaining about half a pound per week now.', momChanges: 'Braxton Hicks may feel stronger. Heartburn might be intense. Small, frequent meals help!', funFact: 'Baby gains about half a pound per week from now on — all that preparation for the outside world!' },
  { week: 33, sizeComparison: 'pineapple', sizeEmoji: '🍍', babyDevelopment: 'The skull is not yet fused — this helps with birth! Baby\'s immune system is getting a boost from antibodies.', momChanges: 'Nesting instinct may kick in! Sleep might be difficult — use pillows for support.', funFact: 'Baby\'s soft, flexible skull is a brilliant design feature — it makes passing through the birth canal easier!' },
  { week: 34, sizeComparison: 'cantaloupe', sizeEmoji: '🍈', babyDevelopment: 'Central nervous system is maturing. Fingernails are fully grown. Fat layers are filling out.', momChanges: 'Group B Strep test usually happens around now. Pack your hospital bag!', funFact: 'Most babies turn head-down around this time — getting into position for their big debut!' },
  { week: 35, sizeComparison: 'honeydew melon', sizeEmoji: '🍈', babyDevelopment: 'Physical development is almost complete! Baby is just adding weight and maturing lungs.', momChanges: 'Breathing might get easier if baby drops into the pelvis. But walking gets harder!', funFact: 'Baby\'s kidneys are fully developed and their liver can process some waste products — almost ready!' },
  { week: 36, sizeComparison: 'head of romaine', sizeEmoji: '🥬', babyDevelopment: 'Lanugo has mostly disappeared. The digestive system has a sterile gut ready for breast milk.', momChanges: 'Weekly OB appointments begin. Signs of labor include regular contractions and water breaking.', funFact: 'You\'re in the final countdown! Every day in the womb now builds crucial brain and lung development.' },
  { week: 37, sizeComparison: 'winter melon', sizeEmoji: '🍉', babyDevelopment: 'FULL TERM! Baby\'s lungs are mature. Most babies are head-down now. All systems are go!', momChanges: 'Labor could start any day! Rest as much as you can and cherish these last moments together.', funFact: 'Your baby is officially full term! All systems are go for life outside the womb.' },
  { week: 38, sizeComparison: 'leek', sizeEmoji: '🌿', babyDevelopment: 'Brain and lungs are still maturing. Baby is shedding the vernix. The gut is filling with meconium.', momChanges: 'You might experience lightning crotch — sharp shooting pains as baby moves lower.', funFact: 'Baby\'s brain will continue developing well into childhood — the learning never stops!' },
  { week: 39, sizeComparison: 'watermelon', sizeEmoji: '🍉', babyDevelopment: 'Baby is ready! Just getting bigger and stronger. The outer layers of skin are peeling as new skin grows.', momChanges: 'Labor is imminent! Stay calm, rest, and call your provider when contractions are regular.', funFact: 'Baby\'s ready for their debut! All that\'s left is choosing the perfect moment to arrive.' },
  { week: 40, sizeComparison: 'small pumpkin', sizeEmoji: '🎃', babyDevelopment: 'Your baby is fully developed and ready to meet the world! Everything is in place for their first breath and cry.', momChanges: 'Due date is here! Only 5% of babies arrive exactly on their due date. Be patient — baby will come!', funFact: 'Happy due date! Your baby\'s first breath will be one of the most beautiful sounds you\'ve ever heard.' },
];

export function getWeekInfo(week: number): WeekInfo {
  const found = pregnancyWeeks.find(w => w.week === week);
  if (found) return found;
  const clamped = Math.min(40, Math.max(4, week));
  return pregnancyWeeks.find(w => w.week === clamped) ?? pregnancyWeeks[pregnancyWeeks.length - 1];
}

export function calculatePregnancyWeek(dueDate: string): number {
  const due = new Date(dueDate);
  const today = new Date();
  const daysUntilDue = Math.floor((due.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
  const currentWeek = 40 - Math.floor(daysUntilDue / 7);
  return Math.max(1, Math.min(42, currentWeek));
}

export function getDaysUntilDueDate(dueDate: string): number {
  const due = new Date(dueDate);
  const today = new Date();
  return Math.max(0, Math.floor((due.getTime() - today.getTime()) / (1000 * 60 * 60 * 24)));
}
